name: Release
on:
  release:
    types: [created]

jobs:
  publish-packages:
    name: Publish all packages
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # Permission for PyPI OIDC token
      id-token: write
    steps:
      # Dependencies
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Setup rust
        run: rustup default stable
      - name: Install node.js dependencies
        run: npm install
      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.6
          actions-cache-folder: 'emsdk-cache'

      # Validation
      - name: Generate parser WASM
        run: npx tree-sitter build-wasm
      - name: Check python package
        run: pip wheel .
      - name: Check rust crate
        run: cargo check
      - name: Test NPM publish scoped package
        run: npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Change node package name
        run: sed -i -e "s/@tlaplus\/tree-sitter-tlaplus/tree-sitter-tlaplus/" package.json
      - name: Test NPM publish global package
        run: npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Test crates.io publish
        run: cargo publish --token ${{secrets.CRATES_AUTH_TOKEN}} --dry-run

      # Publishing
      - name: Upload WASM to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: tree-sitter-tlaplus.wasm
          asset_name: tree-sitter-tlaplus.wasm
          asset_content_type: application/octet-stream
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Publish global package to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Change back node package name
        run: git checkout package.json
      - name: Publish scoped package to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Publish to crates.io
        run: cargo publish --token ${{secrets.CRATES_AUTH_TOKEN}}

      # Downstream Consumers
      - name: Trigger canary workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: canary.yml
          inputs: '{ "version": "${{ github.ref_name }}" }'
      - name: Trigger playground update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: tlaplus-community/tlaplus-community.github.io
          event-type: tree-sitter-tlaplus-release

